### ISSUE TITLE
globals shouldn't be ignored

### ISSUE THREAD

**Issue by stevenvachon** [Woorank/robots-txt-guard#1]
https://github.com/Woorank/robots-txt-guard/blob/master/test/guard.spec.js#L68

That line should return `false`, should it not?

**Comment by Janpot** [comment]
The rules for `agent1` only disallows path `/disallow3` so `/disallow2` is allowed and this line should be `true`

**Comment by stevenvachon** [comment]
`*` applies to all agents.

**Comment by Janpot** [comment]
Yes but only the best matching block is taken into consideration so `*` is ignored because there is `agent1` block. robots.txt files don't cascade.

**Comment by stevenvachon** [comment]
That's not what search engines do.

**Comment by stevenvachon** [comment]
Aye, thanks. I had robots.txt confused with meta tags and http headers.

**Comment by Janpot** [comment]
[For future reference](https://developers.google.com/webmasters/control-crawl-index/docs/robots_txt?hl=en#formal-syntax--definition)

> The start-of-group element user-agent is used to specify for which crawler the group is valid. **Only one group of records is valid for a particular crawler.** We will cover order of precedence later in this document.
